// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIAuthToken API auth token response
//
// swagger:model ApiAuthToken
type APIAuthToken struct {

	// access token
	AccessToken string `json:"access_token"`

	// refresh token
	RefreshToken string `json:"refresh_token"`
}

// Validate validates this Api auth token
func (m *APIAuthToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api auth token based on context it is used
func (m *APIAuthToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAuthToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAuthToken) UnmarshalBinary(b []byte) error {
	var res APIAuthToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
