// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChartSpot Chart point coordinates
//
// swagger:model ChartSpot
type ChartSpot struct {

	// x
	X float64 `json:"x"`

	// y
	Y float64 `json:"y"`
}

// Validate validates this chart spot
func (m *ChartSpot) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chart spot based on context it is used
func (m *ChartSpot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChartSpot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChartSpot) UnmarshalBinary(b []byte) error {
	var res ChartSpot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
