// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChartStyle Chart item style
//
// swagger:model ChartStyle
type ChartStyle struct {

	// opacity
	Opacity float64 `json:"opacity"`

	// primary color
	PrimaryColor int64 `json:"primary_color"`

	// secondary color
	SecondaryColor int64 `json:"secondary_color"`
}

// Validate validates this chart style
func (m *ChartStyle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chart style based on context it is used
func (m *ChartStyle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChartStyle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChartStyle) UnmarshalBinary(b []byte) error {
	var res ChartStyle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
