// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChartAnnotation Chart annotation
//
// swagger:model ChartAnnotation
type ChartAnnotation struct {

	// axis
	Axis string `json:"axis"`

	// end
	End float64 `json:"end"`

	// start
	Start float64 `json:"start"`

	// style
	Style *ChartStyle `json:"style,omitempty"`
}

// Validate validates this chart annotation
func (m *ChartAnnotation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStyle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartAnnotation) validateStyle(formats strfmt.Registry) error {
	if swag.IsZero(m.Style) { // not required
		return nil
	}

	if m.Style != nil {
		if err := m.Style.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("style")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("style")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this chart annotation based on the context it is used
func (m *ChartAnnotation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStyle(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChartAnnotation) contextValidateStyle(ctx context.Context, formats strfmt.Registry) error {

	if m.Style != nil {

		if swag.IsZero(m.Style) { // not required
			return nil
		}

		if err := m.Style.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("style")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("style")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChartAnnotation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChartAnnotation) UnmarshalBinary(b []byte) error {
	var res ChartAnnotation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
