// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckupUpdateRequest Update checkup data
//
// swagger:model CheckupUpdateRequest
type CheckupUpdateRequest struct {

	// checkup
	Checkup *Checkup `json:"checkup,omitempty"`

	// results ids to delete
	ResultsIdsToDelete []int64 `json:"results_ids_to_delete"`

	// results to add
	ResultsToAdd []*Marker `json:"results_to_add"`
}

// Validate validates this checkup update request
func (m *CheckupUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResultsToAdd(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CheckupUpdateRequest) validateCheckup(formats strfmt.Registry) error {
	if swag.IsZero(m.Checkup) { // not required
		return nil
	}

	if m.Checkup != nil {
		if err := m.Checkup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("checkup")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("checkup")
			}
			return err
		}
	}

	return nil
}

func (m *CheckupUpdateRequest) validateResultsToAdd(formats strfmt.Registry) error {
	if swag.IsZero(m.ResultsToAdd) { // not required
		return nil
	}

	for i := 0; i < len(m.ResultsToAdd); i++ {
		if swag.IsZero(m.ResultsToAdd[i]) { // not required
			continue
		}

		if m.ResultsToAdd[i] != nil {
			if err := m.ResultsToAdd[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("results_to_add" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("results_to_add" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this checkup update request based on the context it is used
func (m *CheckupUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCheckup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResultsToAdd(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CheckupUpdateRequest) contextValidateCheckup(ctx context.Context, formats strfmt.Registry) error {

	if m.Checkup != nil {

		if swag.IsZero(m.Checkup) { // not required
			return nil
		}

		if err := m.Checkup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("checkup")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("checkup")
			}
			return err
		}
	}

	return nil
}

func (m *CheckupUpdateRequest) contextValidateResultsToAdd(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ResultsToAdd); i++ {

		if m.ResultsToAdd[i] != nil {

			if swag.IsZero(m.ResultsToAdd[i]) { // not required
				return nil
			}

			if err := m.ResultsToAdd[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("results_to_add" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("results_to_add" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CheckupUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckupUpdateRequest) UnmarshalBinary(b []byte) error {
	var res CheckupUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
