// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Datapoint datapoint
//
// swagger:model Datapoint
type Datapoint struct {

	// timestamp
	Timestamp float64 `json:"timestamp"`

	// value
	Value float64 `json:"value"`
}

// Validate validates this datapoint
func (m *Datapoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datapoint based on context it is used
func (m *Datapoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Datapoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Datapoint) UnmarshalBinary(b []byte) error {
	var res Datapoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
