// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Device User device info
//
// swagger:model Device
type Device struct {

	// adv id
	AdvID string `json:"adv_id,omitempty"`

	// brand
	Brand string `json:"brand,omitempty"`

	// browser
	Browser string `json:"browser,omitempty"`

	// browser version
	BrowserVersion string `json:"browser_version,omitempty"`

	// device id
	DeviceID string `json:"device_id,omitempty"`

	// model
	Model string `json:"model,omitempty"`

	// os
	Os string `json:"os,omitempty"`

	// os version
	OsVersion string `json:"os_version,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// secondary id
	SecondaryID string `json:"secondary_id,omitempty"`
}

// Validate validates this device
func (m *Device) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this device based on context it is used
func (m *Device) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Device) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Device) UnmarshalBinary(b []byte) error {
	var res Device
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
