// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Lab Lab object
//
// swagger:model Lab
type Lab struct {

	// id
	ID int64 `json:"id"`

	// name
	Name string `json:"name"`
}

// Validate validates this lab
func (m *Lab) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this lab based on context it is used
func (m *Lab) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Lab) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Lab) UnmarshalBinary(b []byte) error {
	var res Lab
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
