// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarkerDefinition Marker definition without value and date
//
// swagger:model MarkerDefinition
type MarkerDefinition struct {

	// Marker ID from predefined list
	ID int64 `json:"id"`

	// name
	Name string `json:"name"`

	// reference range
	ReferenceRange *ReferenceRange `json:"reference_range,omitempty"`

	// unit
	Unit *Unit `json:"unit,omitempty"`
}

// Validate validates this marker definition
func (m *MarkerDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReferenceRange(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MarkerDefinition) validateReferenceRange(formats strfmt.Registry) error {
	if swag.IsZero(m.ReferenceRange) { // not required
		return nil
	}

	if m.ReferenceRange != nil {
		if err := m.ReferenceRange.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reference_range")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reference_range")
			}
			return err
		}
	}

	return nil
}

func (m *MarkerDefinition) validateUnit(formats strfmt.Registry) error {
	if swag.IsZero(m.Unit) { // not required
		return nil
	}

	if m.Unit != nil {
		if err := m.Unit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("unit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("unit")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this marker definition based on the context it is used
func (m *MarkerDefinition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReferenceRange(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MarkerDefinition) contextValidateReferenceRange(ctx context.Context, formats strfmt.Registry) error {

	if m.ReferenceRange != nil {

		if swag.IsZero(m.ReferenceRange) { // not required
			return nil
		}

		if err := m.ReferenceRange.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reference_range")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reference_range")
			}
			return err
		}
	}

	return nil
}

func (m *MarkerDefinition) contextValidateUnit(ctx context.Context, formats strfmt.Registry) error {

	if m.Unit != nil {

		if swag.IsZero(m.Unit) { // not required
			return nil
		}

		if err := m.Unit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("unit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("unit")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MarkerDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarkerDefinition) UnmarshalBinary(b []byte) error {
	var res MarkerDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
