// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecognizedMarker recognized marker
//
// swagger:model RecognizedMarker
type RecognizedMarker struct {

	// errors
	Errors *ErrorMessage `json:"errors,omitempty"`

	// marker
	Marker *Marker `json:"marker,omitempty"`
}

// Validate validates this recognized marker
func (m *RecognizedMarker) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMarker(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecognizedMarker) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(m.Errors) { // not required
		return nil
	}

	if m.Errors != nil {
		if err := m.Errors.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errors")
			}
			return err
		}
	}

	return nil
}

func (m *RecognizedMarker) validateMarker(formats strfmt.Registry) error {
	if swag.IsZero(m.Marker) { // not required
		return nil
	}

	if m.Marker != nil {
		if err := m.Marker.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("marker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("marker")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this recognized marker based on the context it is used
func (m *RecognizedMarker) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMarker(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecognizedMarker) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if m.Errors != nil {

		if swag.IsZero(m.Errors) { // not required
			return nil
		}

		if err := m.Errors.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("errors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("errors")
			}
			return err
		}
	}

	return nil
}

func (m *RecognizedMarker) contextValidateMarker(ctx context.Context, formats strfmt.Registry) error {

	if m.Marker != nil {

		if swag.IsZero(m.Marker) { // not required
			return nil
		}

		if err := m.Marker.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("marker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("marker")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecognizedMarker) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecognizedMarker) UnmarshalBinary(b []byte) error {
	var res RecognizedMarker
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
