// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TimeSeriesData Time series data point
//
// swagger:model TimeSeriesData
type TimeSeriesData struct {

	// id
	ID int64 `json:"id"`

	// spots
	Spots []*ChartSpot `json:"spots"`

	// style
	Style *ChartStyle `json:"style,omitempty"`

	// title
	// Example: hemoglobin
	Title string `json:"title"`

	// type
	// Example: line
	Type string `json:"type"`

	// unit
	// Example: g/dL
	Unit string `json:"unit"`
}

// Validate validates this time series data
func (m *TimeSeriesData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpots(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStyle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimeSeriesData) validateSpots(formats strfmt.Registry) error {
	if swag.IsZero(m.Spots) { // not required
		return nil
	}

	for i := 0; i < len(m.Spots); i++ {
		if swag.IsZero(m.Spots[i]) { // not required
			continue
		}

		if m.Spots[i] != nil {
			if err := m.Spots[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spots" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spots" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TimeSeriesData) validateStyle(formats strfmt.Registry) error {
	if swag.IsZero(m.Style) { // not required
		return nil
	}

	if m.Style != nil {
		if err := m.Style.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("style")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("style")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this time series data based on the context it is used
func (m *TimeSeriesData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSpots(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStyle(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimeSeriesData) contextValidateSpots(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Spots); i++ {

		if m.Spots[i] != nil {

			if swag.IsZero(m.Spots[i]) { // not required
				return nil
			}

			if err := m.Spots[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spots" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spots" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TimeSeriesData) contextValidateStyle(ctx context.Context, formats strfmt.Registry) error {

	if m.Style != nil {

		if swag.IsZero(m.Style) { // not required
			return nil
		}

		if err := m.Style.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("style")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("style")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TimeSeriesData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimeSeriesData) UnmarshalBinary(b []byte) error {
	var res TimeSeriesData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
