// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Unit marker result unit object
//
// swagger:model Unit
type Unit struct {

	// description
	Description string `json:"description,omitempty"`

	// full name
	FullName string `json:"full_name,omitempty"`

	// id
	ID int64 `json:"id"`

	// name
	Name string `json:"name"`

	// unrecognized name
	UnrecognizedName string `json:"unrecognized_name,omitempty"`
}

// Validate validates this unit
func (m *Unit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this unit based on context it is used
func (m *Unit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Unit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Unit) UnmarshalBinary(b []byte) error {
	var res Unit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
