// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdatePasswordRequest Update password request by verification code
//
// swagger:model UpdatePasswordRequest
type UpdatePasswordRequest struct {

	// code
	// Format: password
	Code strfmt.Password `json:"code"`

	// new password
	// Format: password
	NewPassword strfmt.Password `json:"new_password"`
}

// Validate validates this update password request
func (m *UpdatePasswordRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdatePasswordRequest) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(m.Code) { // not required
		return nil
	}

	if err := validate.FormatOf("code", "body", "password", m.Code.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UpdatePasswordRequest) validateNewPassword(formats strfmt.Registry) error {
	if swag.IsZero(m.NewPassword) { // not required
		return nil
	}

	if err := validate.FormatOf("new_password", "body", "password", m.NewPassword.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update password request based on context it is used
func (m *UpdatePasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdatePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdatePasswordRequest) UnmarshalBinary(b []byte) error {
	var res UpdatePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
