// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VerifyPhoneRequest VerifyPhoneRequest phone
//
// swagger:model VerifyPhoneRequest
type VerifyPhoneRequest struct {

	// code
	Code string `json:"code"`

	// phone
	Phone string `json:"phone"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *VerifyPhoneRequest) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Code string `json:"code"`

		Phone string `json:"phone"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Code = dataAO0.Code

	m.Phone = dataAO0.Phone

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m VerifyPhoneRequest) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Code string `json:"code"`

		Phone string `json:"phone"`
	}

	dataAO0.Code = m.Code

	dataAO0.Phone = m.Phone

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this verify phone request
func (m *VerifyPhoneRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this verify phone request based on context it is used
func (m *VerifyPhoneRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifyPhoneRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifyPhoneRequest) UnmarshalBinary(b []byte) error {
	var res VerifyPhoneRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
