// Code generated by goro; DO NOT EDIT.

package app

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"errors"
	"github.com/jmoiron/sqlx"
	"labra/internal/usecase"
	"sync"

	"go.uber.org/zap/zapcore"
	"labra/internal/config"
)

type Logger interface {
	Debug(string, ...zapcore.Field)
	Info(string, ...zapcore.Field)
	Error(string, ...zapcore.Field)
	Fatal(string, ...zapcore.Field)
}

type App struct {
	cfg config.Config

	c     *Container
	cOnce *sync.Once

	//hc     health.Checker
	//hcOnce *sync.Once

	mysqlx *sqlx.DB

	logger Logger
}

var a *App

func NewApp(configPath string) (*App, error) {
	cfg, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}

	app := &App{
		cOnce: &sync.Once{},
		//hcOnce: &sync.Once{},
		cfg: cfg,
	}

	//goro:init logger
	app.initLogger()

	//goro:init healthChecker
	//app.initHealthChecker()

	mysqlxConn, err := app.newPostgresConnect(cfg.MainDB)
	if err != nil {
		return nil, err
	}
	app.mysqlx = mysqlxConn

	//goro:init dependencies
	app.c = NewContainer(app.mysqlx, app.cfg)

	return app, nil
}

func (a *App) GetDB() *sqlx.DB {
	return a.mysqlx
}

func (a *App) GetConfig() config.Config {
	return a.cfg
}

func (a *App) UseCases() *usecase.UseCase {
	return a.c.GetUseCase()
}

func SetGlobalApp(app *App) {
	a = app
}

func GetGlobalApp() (*App, error) {
	if a == nil {
		return nil, errors.New("global app is not initialized")
	}

	return a, nil
}
