version: '3.9'

services:
  labra:
    image: ghcr.io/hanagantig/labra:${CI_COMMIT_SHORT_SHA}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.labra-api.rule=Host(`api.labra.ae`)"
      - "traefik.http.routers.labra-api.entrypoints=websecure"
      - "traefik.http.services.labra-api.loadbalancer.server.port=80"

volumes:
  sqlite-data:

networks:
  internal:
    external: true