// Code generated by goro;

package marker

// This file was generated by the goro tool.

import (
	"github.com/jmoiron/sqlx"

	"labra/internal/adapter/mysqlxrepo"
)

type Repository struct {
	mysqlxrepo.Transactor
}

func NewRepository(conn *sqlx.DB) *Repository {
	return &Repository{
		mysqlxrepo.NewTransactor(conn),
	}
}
